name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Setup Python (faster than using Python container)
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.7"

    - name: Install pipenv
      run: |
          python -m pip install --upgrade pipenv wheel
          
    - id: cache-pipenv
      uses: actions/cache@v1
      with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache-pipenv.outputs.cache-hit != 'true'
      run: |
          pipenv install --deploy --dev
          pipenv install coverage
    - name: Install and run linter
      run: |
        pip install pylint
        pylint --exit-zero `ls -R|grep .py$|xargs`
    - name: Execute unit tests
      run: |
        pipenv run coverage run --source=. -m unittest discover -v
    - name: Check code coverage
      run: |
        pipenv run coverage report
